
name: pages build and deployment

on:
  push:
    branches: [ "master" ]

# Environment variables available to all jobs and steps in this workflow.
# env:
#   REGION_ID: cn-hangzhou
#   REGISTRY: registry.cn-hangzhou.aliyuncs.com
#   NAMESPACE: namespace
#   IMAGE: repo
#   TAG: ${{ github.sha }}
#   ACK_CLUSTER_ID: clusterID
#   ACK_DEPLOYMENT_NAME: nginx-deployment

#   ACR_EE_REGISTRY: myregistry.cn-hangzhou.cr.aliyuncs.com
#   ACR_EE_INSTANCE_ID: instanceID
#   ACR_EE_NAMESPACE: namespace
#   ACR_EE_IMAGE: repo
#   ACR_EE_TAG: ${{ github.sha }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    # - name: Pull ghcr.io/actions/jekyll-build-pages:v1.0.9
    #   run: |
    #     Pull down action image 'ghcr.io/actions/jekyll-build-pages:v1.0.9'
        
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: master
        submodules: recursive
        repository: HopangLee/HopangLee.github.io
        ssh-strict: true
        persist-credentials: true
        clean: true
        sparse-checkout-cone-mode: true
        fetch-depth: 1
        fetch-tags: false
        lfs: false
        set-safe-directory: true
      
    - name: Build with Jekyll
      uses: actions/jekyll-build-pages@v1
      with:
        source: .
        destination: ./_site
        future: false
        build_revision: 81df6075afbfb9dbb2f13957e6e1282c4c9a82d9
        verbose: true

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        name: github-pages
        path: ./_site
        retention-days: 1

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Github Pages
      uses: actions/deploy-pages@v2
      with:
        timeout: 600000
        error_count: 10
        reporting_interval: 5000
        artifact_name: github-pages
        preview: false
        token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
